name: PR Check
on: push
jobs:
  test-linting:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Test linting
        run: npm run lint
